spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    url: jdbc:mysql://localhost:3306/askbook
    password:
  redis:
    port: 6379
    password:
    host: 127.0.0.1
    database: 0 #连接那个数据库
    jedis:
      pool:
        max-active: 8  #最大连接数
        max-wait: 1ms  #连接池最大阻塞状态
        max-idle: 4  #连接池最大空闲连接
        min-idle: 0  #连接池最小空闲连接
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    banner: false
server:
  port: 6060
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: GBK
imagePath:
  /usr/askbook/images
tencent:
  sms:
    secretId:
    secretKey:
  cos:
    secretId:
    secretKey:
    buckerName:
    region:
    url:
